name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'protegeproject-bot' }}
    steps:
      - run: echo ${{github.actor}}
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PROTEGEPROJECT_BOT_APP_ID }}
          private-key: ${{ secrets.PROTEGEPROJECT_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
      - run: echo ${{github.actor}}
      
